/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/officemacdesk2.glb -K -k
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/officemacdesk2.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="1f289cf8a7274f02b6b6a18f79082eadfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="RootNode">
              <group name="pCube3" position={[-5.85, 10.37, -16.3]} scale={0.05}>
                <group name="polySurface60">
                  <mesh name="polySurface60_Display_Shader_0" geometry={nodes.polySurface60_Display_Shader_0.geometry} material={materials.Display_Shader} />
                  <mesh name="polySurface60_MonitorBlack_Shader_0" geometry={nodes.polySurface60_MonitorBlack_Shader_0.geometry} material={materials.MonitorBlack_Shader} />
                  <mesh name="polySurface60_MonitorChrome_Shader_0" geometry={nodes.polySurface60_MonitorChrome_Shader_0.geometry} material={materials.MonitorChrome_Shader} />
                </group>
                <group name="polySurface61">
                  <mesh name="polySurface61_aiStandardSurface11_0" geometry={nodes.polySurface61_aiStandardSurface11_0.geometry} material={materials.aiStandardSurface11} />
                </group>
              </group>
              <group name="pCube4" position={[-15.44, 10.49, -1.46]} rotation={[-Math.PI, 1.15, -Math.PI]} scale={[4.04, 0.18, 6.2]}>
                <mesh name="pCube4_Tablet_Stylus_Shader_0" geometry={nodes.pCube4_Tablet_Stylus_Shader_0.geometry} material={materials.Tablet_Stylus_Shader} />
              </group>
              <group name="pCube6" position={[-17.06, 10.89, -3.01]} rotation={[Math.PI, -Math.PI / 4, Math.PI]} scale={[0.08, 0.08, 0.07]} />
              <group name="pCylinder18" position={[-14.1, 10.47, 1.12]} rotation={[0, 0.55, Math.PI / 2]} scale={[0.09, 1.65, 0.09]}>
                <mesh name="pCylinder18_Tablet_Stylus_Shader_0" geometry={nodes.pCylinder18_Tablet_Stylus_Shader_0.geometry} material={materials.Tablet_Stylus_Shader} />
              </group>
              <group name="pCylinder20" position={[1.91, 0, 0]} />
              <group name="polySurface1" position={[0, -5.25, 7.94]} scale={2.69}>
                <mesh name="polySurface1_lambert1_0" geometry={nodes.polySurface1_lambert1_0.geometry} material={materials.lambert1} />
                <mesh name="polySurface1_TableCeramic_Shader_0" geometry={nodes.polySurface1_TableCeramic_Shader_0.geometry} material={materials.TableCeramic_Shader} />
                <mesh name="polySurface1_TableWood_Shader_0" geometry={nodes.polySurface1_TableWood_Shader_0.geometry} material={materials.TableWood_Shader} />
              </group>
              <group name="polySurface36" position={[-4.56, 0, 2.19]} rotation={[0, 0.4, 0]} />
              <group name="polySurface4" position={[0.75, -5.29, 8.17]} scale={2.69}>
                <mesh name="polySurface4_lambert1_0" geometry={nodes.polySurface4_lambert1_0.geometry} material={materials.lambert1} />
              </group>
              <group name="polySurface5" position={[0.3, -4.36, 8.85]} rotation={[0, 0.03, 0]} scale={2.58}>
                <mesh name="polySurface5_BBookpaper_Shader_0" geometry={nodes.polySurface5_BBookpaper_Shader_0.geometry} material={materials.BBookpaper_Shader} />
                <mesh name="polySurface5_BBookRoot_Shader_0" geometry={nodes.polySurface5_BBookRoot_Shader_0.geometry} material={materials.BBookRoot_Shader} />
              </group>
              <group name="polySurface6" position={[0.7, -5.25, 7.66]} scale={2.69}>
                <mesh name="polySurface6_Mouse_Shader_0" geometry={nodes.polySurface6_Mouse_Shader_0.geometry} material={materials.Mouse_Shader} />
              </group>
              <group name="polySurface62" position={[24.59, -3.93, -8.24]} rotation={[0, 0.8, 0]} scale={2.58} />
              <group name="polySurface7" position={[0, -5.08, 8.17]} rotation={[-0.01, 0, 0]} scale={2.69}>
                <mesh name="polySurface7_Keyboard_Shader_0" geometry={nodes.polySurface7_Keyboard_Shader_0.geometry} material={materials.Keyboard_Shader} />
                <mesh name="polySurface7_KeyboardDown_Shader_0" geometry={nodes.polySurface7_KeyboardDown_Shader_0.geometry} material={materials.KeyboardDown_Shader} />
              </group>
              <group name="polySurface9" position={[5.74, 11.74, -4.51]} scale={0.02} />
            </group>
          </group>
        </group>
        <group name="Empty" position={[-0.07, -0.08, 0.14]} rotation={[-Math.PI, 0.04, -Math.PI]} scale={0.25}>
          <group name="Armature">
            <primitive object={nodes.Hips} />
          </group>
          <skinnedMesh name="Wolf3D_Body" geometry={nodes.Wolf3D_Body.geometry} material={materials.Wolf3D_Body} skeleton={nodes.Wolf3D_Body.skeleton} />
          <skinnedMesh name="Wolf3D_Hair" geometry={nodes.Wolf3D_Hair.geometry} material={materials.Wolf3D_Hair} skeleton={nodes.Wolf3D_Hair.skeleton} />
          <skinnedMesh name="Wolf3D_Outfit_Bottom" geometry={nodes.Wolf3D_Outfit_Bottom.geometry} material={materials.Wolf3D_Outfit_Bottom} skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton} />
          <skinnedMesh name="Wolf3D_Outfit_Footwear" geometry={nodes.Wolf3D_Outfit_Footwear.geometry} material={materials.Wolf3D_Outfit_Footwear} skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton} />
          <skinnedMesh name="Wolf3D_Outfit_Top" geometry={nodes.Wolf3D_Outfit_Top.geometry} material={materials.Wolf3D_Outfit_Top} skeleton={nodes.Wolf3D_Outfit_Top.skeleton} />
          <skinnedMesh name="EyeLeft" geometry={nodes.EyeLeft.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.EyeLeft.skeleton} morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary} morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences} />
          <skinnedMesh name="EyeRight" geometry={nodes.EyeRight.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.EyeRight.skeleton} morphTargetDictionary={nodes.EyeRight.morphTargetDictionary} morphTargetInfluences={nodes.EyeRight.morphTargetInfluences} />
          <skinnedMesh name="Wolf3D_Head" geometry={nodes.Wolf3D_Head.geometry} material={materials.Wolf3D_Skin} skeleton={nodes.Wolf3D_Head.skeleton} morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences} />
          <skinnedMesh name="Wolf3D_Teeth" geometry={nodes.Wolf3D_Teeth.geometry} material={materials.Wolf3D_Teeth} skeleton={nodes.Wolf3D_Teeth.skeleton} morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/officemacdesk2.glb')
